In [665]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

data = pd.read_excel("data.xlsx")
X = data.iloc[:, 1].values.reshape(-1, 1)
y = data.iloc[:, 2].values.reshape(-1, 1)

scaler1 = MinMaxScaler(feature_range=(-1,1))
X = scaler1.fit_transform(X)
scaler2 = MinMaxScaler(feature_range=(-1,1))
y = scaler2.fit_transform(y)
# scaler = 
# plt.plot(X, y, "ro")
# plt.show()

In [666]:
def fitness(w):
    res = []
    for c in w:
        res.append(np.sum(np.square(y-(c * X)))/6)
    return np.array(res)

In [667]:
populationSize = (100, 1)
population = np.random.uniform(low=-1, high=1,size=(populationSize[0], populationSize[1]))

In [668]:
f1 = fitness(population)

In [669]:
def selection(pop):
    f1 = fitness(population)
    pop = pop[np.argsort(f1)][:int(len(pop) * 0.2)]
    return pop
# selection(population)

In [670]:
def crossover(p1, p2):
    return (p1 + p2) / 2

In [671]:
def mutate(individual):
    new = individual + np.random.uniform(-0.1, 0.1)
    return new

In [672]:
MUTATION_RATE = 0.5
EPOCHS = 10000
his = []
for i in range (EPOCHS):
    selected = selection(population)
    new_population = []
    while(len(new_population) < populationSize[0]):
        parent1 = selected[np.random.randint(0, len(selected))]
        parent2 = selected[np.random.randint(0, len(selected))]
        child = crossover(parent1, parent2)
        if np.random.random() < MUTATION_RATE:
            child = mutate(child)
        new_population.append(child)
    his.append(new_population[0])

In [673]:
his

[array([0.84769741]),
 array([0.66227701]),
 array([0.88257464]),
 array([0.79657901]),
 array([0.95781964]),
 array([0.6667087]),
 array([0.77943285]),
 array([0.82277549]),
 array([0.8950239]),
 array([0.64801959]),
 array([0.81225502]),
 array([0.74931561]),
 array([0.81263233]),
 array([0.95318843]),
 array([0.80785232]),
 array([0.98804569]),
 array([0.84968889]),
 array([0.65995895]),
 array([0.70498159]),
 array([0.73696814]),
 array([0.80370224]),
 array([0.82781111]),
 array([0.81330501]),
 array([0.69351635]),
 array([0.74592144]),
 array([0.74531186]),
 array([0.87425568]),
 array([0.7873543]),
 array([0.68226191]),
 array([0.70261552]),
 array([0.80676405]),
 array([0.82436759]),
 array([0.66235198]),
 array([0.76351071]),
 array([0.82277549]),
 array([0.75070159]),
 array([0.82923613]),
 array([0.66174241]),
 array([0.85599608]),
 array([0.82456061]),
 array([0.8528598]),
 array([0.76421779]),
 array([0.90438292]),
 array([0.75902197]),
 array([0.96317617]),
 array([0.7503

In [674]:
new_population[0]

array([0.87000239])

In [675]:
# plt.plot(X, y, "ro")
# plt.plot(X, new_population[0]*X)
# plt.show()

In [676]:
from matplotlib.animation import FuncAnimation
%matplotlib qt
fig, ax = plt.subplots()
xdata, ydata = [], []
ln, = plt.plot([], [], '-g')
ln2, = plt.plot(X, y, 'ro')

def init():
    ax.set_xlim(-1.1, 1.1)
    ax.set_ylim(-1.1, 1.1)
    return ln, ln2,

def update(frame):
    ln.set_data(X, frame * X)
    return ln, ln2,

ani = FuncAnimation(fig, update, frames=his,
                    init_func=init, blit=True, repeat=False, interval=10)
plt.show()