In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

train_data = pd.read_excel("data.xlsx", "train")
test_data = pd.read_excel("data.xlsx", "test")

X_train = train_data.iloc[:, 5:].values
X_test = test_data.iloc[:, 5:].values

y_train = train_data.iloc[:, 1:5].values
y_test = test_data.iloc[:, 1:5].values

In [11]:
print(y_train.shape)
X_train.shape

(7, 4)


(7, 5)

In [12]:
A = np.linalg.inv((X_train.T @ X_train)) @ X_train.T @ y_train
y_pred = X_test @ A
# In ra màn hình kết quả nồng độ dự đoán
print(pd.DataFrame(y_pred, columns = train_data.iloc[:, 1:5].columns))
# In ra màn hình % sai số giữa nồng độ dự đoán so với nồng độ các dạng As trong tập test
print(pd.DataFrame(np.abs(y_test - y_pred) / y_test * 100, 
                   columns = train_data.iloc[:, 1:5].columns))

    As(III)      As(V)       DMA       MMA
0  2.813440   7.262627  4.324158  2.233893
1  2.906440   7.635763  2.764133  3.392223
2  4.337868  10.370115  0.681186  5.217134
     As(III)      As(V)        DMA        MMA
0  12.537583  21.043779   3.907593  10.644297
1   3.118677   9.082330   7.862245  13.074090
2   3.602929   3.701154  31.881415   4.342673


In [13]:
print(np.abs(y_test - y_pred) / y_test * 100)

[[12.5375835  21.04377941  3.90759283 10.64429742]
 [ 3.11867747  9.0823305   7.86224497 13.07408981]
 [ 3.6029288   3.70115379 31.88141546  4.34267287]]


In [14]:
X_train = np.concatenate((X_train, np.ones((X_train.shape[0], 1))), axis=1)
X_test = np.concatenate((X_test, np.ones((X_test.shape[0], 1))), axis=1)
print(X_train.shape, X_test.shape)

(7, 6) (3, 6)


In [15]:
A = np.linalg.inv((X_train.T @ X_train)) @ X_train.T @ y_train
y_pred = X_test @ A
# In ra màn hình kết quả nồng độ dự đoán
print(pd.DataFrame(y_pred, columns = train_data.iloc[:, 1:5].columns))
# In ra màn hình % sai số giữa nồng độ dự đoán so với nồng độ các dạng As trong tập test
print(pd.DataFrame(np.abs(y_test - y_pred) / y_test * 100, 
                   columns = train_data.iloc[:, 1:5].columns))

    As(III)     As(V)       DMA       MMA
0  2.859239  7.067703  4.388340  2.306666
1  2.885436  7.725155  2.734699  3.358849
2  4.451463  9.886655  0.840372  5.397630
     As(III)      As(V)        DMA        MMA
0  14.369564  17.795053   2.481341   7.733366
1   3.818795  10.359350   8.843357  11.961636
2   1.078608   1.133447  15.962814   7.952598
